# docker build -t transpiler-battle-ts --file Dockerfile-typescript .
# docker run -p 1337:1337 -it --rm -v /Users/janhalozan/Work/GitHub/TranspilerBattle/:/usr/app/ --name tbt transpiler-battle-ts

FROM node:7.0.0

# RUN apt-get update && \
#     apt-get install -y -qq

RUN npm install -g pm2@latest typescript

COPY . /usr/app
WORKDIR /usr/app
RUN npm install --only=prod && npm install --only=dev

CMD ["npm", "run", "starttype"]
