# docker build -t transpiler-battle-babel --file Dockerfile-babel .
# docker run -p 1337:1337 -it --rm -v /Users/janhalozan/Work/GitHub/TranspilerBattle/:/usr/app/ --name tbb transpiler-battle-babel

FROM node:7.0.0

# RUN apt-get update && \
#     apt-get install -y -qq

RUN npm install -g pm2@latest babel-cli

COPY . /usr/app
WORKDIR /usr/app
RUN npm install

CMD ["npm", "run", "startbabel"]
