// Generated by CoffeeScript 1.12.2
(function() {
  var app, bodyParser, express, port;

  express = require('express');

  bodyParser = require('body-parser');

  app = express();

  port = process.env.port || 1337;

  app.use(bodyParser.json());

  app.get('/', function(req, res) {
    return res.send('Hello world');
  });

  app.post('/light', function(req, res) {
    var highResTime, microtime;
    highResTime = process.hrtime();
    microtime = highResTime[0] * 1000000 + highResTime[1] / 1000;
    return res.send(req.body.message + ' at: ' + microtime.toString());
  });

  app.listen(port, function() {
    return console.log('Listening on ' + port);
  });

}).call(this);
